extends: standard
plugins:
  - angular
  - standard
  - promise
env: 
  browser: 1
globals:
  angular: true
rules:
  angular/avoid-scope-typos: 2
  angular/module-getter: 2
  angular/module-setter: 2
  angular/no-private-call: 2
  angular/no-cookiestore: 2
  angular/no-directive-replace: 2
  angular/no-http-callback : 2
  angular/di: 
    - 2
    - array
  brace-style: 
    - 2
    - stroustrup
  no-console: 2
  semi: 
    - 2
    - always
  space-before-function-paren: 0
settings:
    angular: 1
